image: "${GLOBAL_IMAGE_NAME}:${GLOBAL_IMAGE_TAG}"

# https://gitlab.com/singletonsd/pipelines/angular
include:
  - project: 'singletonsd/pipelines/angular'
    file: '/src/.gitlab-ci-app.yml'

variables:
  GLOBAL_IMAGE_NAME: "node"
  GLOBAL_IMAGE_TAG: "8-alpine"
  TEST_STATIC_ALL: "true"
  ORIGINAL_REPOSITORY: patricioperpetua/web
  NG_APP_AWS_S3_DEPLOY: "true"
  NG_APP_AWS_S3_REGION: eu-west-3
  NG_APP_AWS_S3_ACCESS_KEY_ID: "${AMAZON_S3_RESUME_WR_ACCESS_KEY_ID}"
  NG_APP_AWS_S3_SECRET_ACCESS_KEY: "${AMAZON_S3_RESUME_WR_SECRET_ACCESS_KEY}"

stages:
  - install
  - test_static
  - build
  - test_dynamic
  - pre_deploy
  - analysis
  - deploy

performance:
  stage: analysis
  image: docker:git
  variables:
    URL: https://patricioperpetua.com
  services:
    - docker:stable-dind
  before_script: []
  script:
    - mkdir gitlab-exporter
    - wget -O ./gitlab-exporter/index.js https://gitlab.com/gitlab-org/gl-performance/raw/master/index.js
    - mkdir sitespeed-results
    - docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:6.3.1 --plugins.add ./gitlab-exporter --outputFolder sitespeed-results $URL
    - mv sitespeed-results/data/performance.json performance.json
    - mkdir -p dist/sitespeed
    - mv -r sitespeed-results dist/sitespeed
  artifacts:
    name: "$CI_PROJECT_NAME-${CI_COMMIT_REF_NAME}-sitespeed"
    paths:
      - dist
    reports:
      performance: performance.json
  only:
    variables:
      - $CI_PROJECT_PATH == $ORIGINAL_REPOSITORY
      - $TRIGGER_EXECUTION == "DAILY"

pwmetrics:
  stage: analysis
  image: registry.gitlab.com/singletonsd/docker/puppeteer
  before_script:
    - mkdir -p ~/.credentials
    - echo "${GOOGLE_SHEETS_CREDENTIALS}" > ~/.credentials/sheets.googleapis.com-nodejs-pwmetrics.json
    - echo ${REGISTRY_GITLAB_USER} > ~/.credentials/sheets.googleapis.com-nodejs-pwmetrics.json
  script:
    - npm i
    - npm run analyze-pwmetrics
  only:
    variables:
      - $CI_PROJECT_PATH == $ORIGINAL_REPOSITORY
      - $TRIGGER_EXECUTION == "DAILY"

bundle:
  stage: analysis
  script:
    - rm -rf dist/dist
    - npm run analyze-bundle
    - mkdir -p dist/bundle
    - mv dist/dist/stats.json dist/bundle/stats.json
    - rm -rf dist/dist
  artifacts:
    name: "$CI_PROJECT_NAME-${CI_COMMIT_REF_NAME}"
    paths:
      - dist
