image: "${GLOBAL_IMAGE_NAME}:${GLOBAL_IMAGE_TAG}"

variables:
  GLOBAL_IMAGE_NAME: "node"
  GLOBAL_IMAGE_TAG: "8-alpine"
  TEST_STATIC_ALL: "true"
  ORIGINAL_REPOSITORY: patricioperpetua/web

include:
  - project: 'singletonsd/pipelines/npm'
    file: '/src/.gitlab-ci-test-static.yml'

stages:
  - install
  - test_static
  - build
  - test
  - pre_deploy
  - analysis
  - deploy

install:
  stage: install
  before_script: []
  script:
    - npm install --no-optional
  except:
    - schedules
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - rm -rf dist/
    - npm run build
    - mv dist/dist dist/dist-root
  artifacts:
    name: "$CI_PROJECT_NAME-${CI_COMMIT_REF_NAME}-built"
    paths:
      - dist
  except:
    - schedules

test:
  before_script:
    - apk --no-cache add chromium xvfb
    - export CHROME_BIN=/usr/bin/chromium-browser
    - export CHROME_PATH=/usr/lib/chromium/
    # Launch Xvfb
    - Xvfb :0 -ac -screen 0 1024x768x24 &
    # Export display for Chrome
    - export DISPLAY=:99
    - npm install -g @angular/cli --no-optional
  stage: test
  script:
    - echo test
    # - ng test
    # - ng e2e
  except:
    - schedules

amazon_s3:
  image: python:3.7.3-alpine3.10
  stage: pre_deploy
  variables:
    AWS_DEFAULT_REGION: eu-west-3 # The region of S3 bucket
    AWS_ACCESS_KEY_ID: ${AMAZON_S3_RESUME_WR_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AMAZON_S3_RESUME_WR_SECRET_ACCESS_KEY}
  before_script:
    - apk add --no-cache bash
    - pip install awscli # Install the SDK
  script:
    - ./scripts/uploader_amazon_s3.sh
  except:
    - schedules
  only:
    variables:
      - $CI_PROJECT_PATH == $ORIGINAL_REPOSITORY

deploy-image-branches:
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_REGISTRY: ${CI_REGISTRY_IMAGE}
  stage: pre_deploy
  before_script:
    - docker login registry.gitlab.com -u ${REGISTRY_GITLAB_USER} -p ${REGISTRY_GITLAB_PASS}
    - apk add --no-cache bash curl gawk git sed util-linux pciutils usbutils coreutils binutils findutils grep
  script:
    - if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then
        export DOCKER_IMAGE_TAG=latest;
      else
        export DOCKER_IMAGE_TAG=${CI_COMMIT_REF_NAME};
      fi
    - ./scripts/generate_docker_image.sh ${DOCKER_REGISTRY} ${DOCKER_IMAGE_TAG} ${CI_COMMIT_SHA} 1
  when: on_success
  except:
    - schedules

performance:
  stage: analysis
  image: docker:git
  variables:
    URL: https://patricioperpetua.com
  services:
    - docker:stable-dind
  before_script: []
  script:
    - mkdir gitlab-exporter
    - wget -O ./gitlab-exporter/index.js https://gitlab.com/gitlab-org/gl-performance/raw/master/index.js
    - mkdir sitespeed-results
    - docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:6.3.1 --plugins.add ./gitlab-exporter --outputFolder sitespeed-results $URL
    - mv sitespeed-results/data/performance.json performance.json
  artifacts:
    name: "$CI_PROJECT_NAME-${CI_COMMIT_REF_NAME}-sitespeed"
    paths:
      - sitespeed-results/
    reports:
      performance: performance.json
  only:
    variables:
      - $CI_PROJECT_PATH == $ORIGINAL_REPOSITORY
      - $TRIGGER_EXECUTION == "DAILY"

pwmetrics:
  stage: analysis
  image: registry.gitlab.com/singletonsd/docker/puppeteer
  before_script:
    - mkdir -p ~/.credentials
    - echo "${GOOGLE_SHEETS_CREDENTIALS}" > ~/.credentials/sheets.googleapis.com-nodejs-pwmetrics.json
    - echo ${REGISTRY_GITLAB_USER} > ~/.credentials/sheets.googleapis.com-nodejs-pwmetrics.json
  script:
    - npm i
    - npm run analyze-pwmetrics
  only:
    variables:
      - $CI_PROJECT_PATH == $ORIGINAL_REPOSITORY
      - $TRIGGER_EXECUTION == "DAILY"

bundle:
  stage: analysis
  script:
    - rm -rf dist/dist
    - npm run analyze-bundle
    - mkdir -p dist/bundle
    - mv dist/dist/stats.json dist/bundle/stats.json
    - rm -rf dist/dist
  artifacts:
    name: "$CI_PROJECT_NAME-${CI_COMMIT_REF_NAME}"
    paths:
      - dist/bundle/stats.json

pages:
  stage: deploy
  script:
    - mkdir -p public/reports/sitespeed
    - mkdir -p public/reports/bundle
    - cp -r dist/dist-root/* public || true
    - cp -r sitespeed-results/* public/reports/sitespeed || true
    - cp dist/bundle/stats.json public/reports/bundle/stats.json || true
    - ls -R public
  artifacts:
    name: "$CI_PROJECT_NAME-${CI_COMMIT_REF_NAME}"
    paths:
      - public
  only:
  - master
